### ISSUE TITLE
an error on "RTA with multiple signatures (two passes)”

### ISSUE THREAD

**Issue by cpusoft** [APNIC-net/rpki-rta-demo#1]
when I test the script : "# resign-rta --ca-name ca2 --in rta --out rta" in “RTA with multiple signatures (two passes)”  ,  an error is reported:

#resign-rta --ca-name ca2 --in rta --out rta
write_file '/root/rta/RTAwithmultiplesignatures_twopass//root/rta/RTAwithmultiplesignatures_twopass/rta' - sysopen: No such file or directory at /usr/local/bin/resign-rta line 94.

this script directory is on /root/rta/RTAwithmultiplesignatures_twopass in Docker 

thx

**Comment by tomhrr** [comment]
Thanks, this has been fixed.
